ischeme.out: ischeme.cpp\
   			Utils.hpp Tokenize.hpp SExpression.hpp SObject.hpp SScope.hpp BuiltIn.hpp\
   			SObject.cpp Tokenize.cpp Utils.cpp SExpression.cpp BuiltIn.cpp
	g++ ischeme.cpp SObject.cpp Tokenize.cpp Utils.cpp SExpression.cpp BuiltIn.cpp -o ischeme.out
