ischeme.out: ischeme.cpp Utils.hpp Tokenize.hpp SExpression.hpp SObject.hpp SScope.hpp\
   			SObject.cpp Tokenize.cpp Utils.cpp SExpression.cpp
	g++ ischeme.cpp SObject.cpp Tokenize.cpp Utils.cpp SExpression.cpp -o ischeme.out
